development:
  adapter: mysql2
  database: my_net
  user: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: my_net_test
  user: root
  password:
  pool: 5
  timeout: 5000


##ps
#development:
#  adapter: postgresql
#  encoding: unicode
#  database: my_net
#  pool: 5
#  username: meter
#  password:
#
#test:
#  adapter: postgresql
#  encoding: unicode
#  database: my_net_test
#  pool: 5
#  username: meter
#  password:
